%EE569 HOMEWORK ASSIGNMENT 3
%DATE: Mar 11th 2021
%NAME: Siyu Li
%ID:2455870216
%E-mail:lisiyu@usc.edu
function existanceMap = stage2Filter_ST(stage1result)
[m,n] = size(stage1result);
existanceMap = zeros(m,n);
stage1resultPad = hw3zeroPadding(stage1result, 1);
for i=1:m
    for j=1:n
        if stage1resultPad(i + 1,j + 1) == 1
            
            % spur
            spur1 = ~stage1resultPad(i ,j) && ~stage1resultPad(i,j + 1) && stage1resultPad(i,j+2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            spur2 = stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
            % Single 4-connection
            single4c1 = ~stage1resultPad(i ,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            single4c2 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
            % L Cluster
            LCluster11 = ~stage1resultPad(i ,j) && ~stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster12 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster13 = stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster14 = stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j ) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster21 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster22 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            LCluster23 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && stage1resultPad(i + 2,j + 2);
             
            LCluster24 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && stage1resultPad(i + 2,j + 2);
            % 4-connected Offset
            COffset1 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            COffset2 = stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            COffset3 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && stage1resultPad(i + 2,j + 2);
             
            COffset4 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
            % Spur corner Cluster
            SpurcornerCluster1 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j ) && ...
                 stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i,j + 1) || stage1resultPad(i + 1,j + 2));
             
            SpurcornerCluster2 = stage1resultPad(i,j) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1) && stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i + 1, j) || stage1resultPad(i,j + 1));
             
            SpurcornerCluster3 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j + 2) && ...
                 stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i + 1,j) || stage1resultPad(i + 2,j + 1));
             
            SpurcornerCluster4 = stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1,j) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i + 1, j + 2) || stage1resultPad(i + 2,j + 1));
             % Corner Cluster
             CornerCluster1 = stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ...
                 stage1resultPad(i + 1,j);
             CornerCluster2 = stage1resultPad(i+1,j+2) && stage1resultPad(i+2,j + 1) && ...
                 stage1resultPad(i + 2,j+2);
             % Tee Branch
             TeeBranch11 = stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
             TeeBranch12 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ...
                 stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && ~stage1resultPad(i + 2,j + 1);
             
            TeeBranch13 = ~stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ...
                 stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1);
             
            TeeBranch14 = ~stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            TeeBranch21 = stage1resultPad(i,j + 1) && ...
                 stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
             
            TeeBranch22 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j + 1);
             
            TeeBranch23 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j + 1);
             
            TeeBranch24 = stage1resultPad(i,j + 1) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);
            % Vee Branch
            VeeBranch1 = stage1resultPad(i,j) && stage1resultPad(i,j + 2) && ...
                 (stage1resultPad(i + 2,j) || stage1resultPad(i + 2,j + 1) || stage1resultPad(i + 2,j + 2));
             
            VeeBranch2 = stage1resultPad(i,j) && ...
                 stage1resultPad(i + 2,j) && ...
                 (stage1resultPad(i,j + 2) || stage1resultPad(i + 1,j + 2) || stage1resultPad(i + 2,j + 2));
             
            VeeBranch3 = stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i,j) || stage1resultPad(i,j + 1) || stage1resultPad(i,j + 2));
             
            VeeBranch4 = stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 2,j + 2) && ...
                 (stage1resultPad(i,j) || stage1resultPad(i + 1, j) || stage1resultPad(i + 2,j));
            % Diagonal Branch
            DiagonalBranch1 = stage1resultPad(i,j + 1) && ~stage1resultPad(i,j + 2) && ...
                 ~stage1resultPad(i + 1, j ) && stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j ) && ~stage1resultPad(i + 2,j + 1);
             
            DiagonalBranch2 = ~stage1resultPad(i,j) && stage1resultPad(i,j + 1) && ...
                 stage1resultPad(i + 1, j) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j + 1) && stage1resultPad(i + 2,j + 2);
             
            DiagonalBranch3 = ~stage1resultPad(i,j + 1) && stage1resultPad(i,j + 2) && ...
                 stage1resultPad(i + 1, j ) && ~stage1resultPad(i + 1,j + 2) && ...
                 ~stage1resultPad(i + 2,j) && stage1resultPad(i + 2,j + 1);
             
            DiagonalBranch4 = stage1resultPad(i,j) && ~stage1resultPad(i,j + 1) && ...
                 ~stage1resultPad(i + 1, j) && stage1resultPad(i + 1,j + 2) && ...
                 stage1resultPad(i + 2,j + 1) && ~stage1resultPad(i + 2,j + 2);

            existanceMap(i,j) = ~(spur1 || spur2 || single4c1 || single4c2 || LCluster11 || LCluster12 || LCluster13 || LCluster14 || LCluster21 || LCluster22 || LCluster23 || LCluster24 || ...
                COffset1 || COffset2 || COffset3 || COffset4 || SpurcornerCluster1 || SpurcornerCluster2 || SpurcornerCluster3 || SpurcornerCluster4 || CornerCluster1 || CornerCluster2 || TeeBranch11 || TeeBranch12 || TeeBranch13 || TeeBranch14 || TeeBranch21 || TeeBranch22 || ...
                TeeBranch23 || TeeBranch24 || VeeBranch1 || VeeBranch2 || VeeBranch3 || VeeBranch4 || DiagonalBranch1 || DiagonalBranch2 || DiagonalBranch3 || DiagonalBranch4);
        end
    end
end
















end